package com.moolah.moolah_core.models;

import java.time.LocalDateTime;

import lombok.Data;

@Data
public class User {
    // Fields
    private Long id;
    private Long roleId;
    private String username;
    private String email;
    private String passwordHash;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // Getters and Setters
    // - generated by @Data in Lombok
    // public Long getId() {
    //     return id;
    // }
    // public void setId(Long id) {
    //     this.id = id;
    // }
    // public Long getRoleId() {
    //     return roleId;
    // }
    // public void setRoleId(Long roleId) {
    //     this.roleId = roleId;
    // }
    // public String getUsername() {
    //     return username;
    // }
    // public void setUsername(String username) {
    //     this.username = username;
    // }
    // public String getEmail() {
    //     return email;
    // }
    // public void setEmail(String email) {
    //     this.email = email;
    // }
    // public String getPasswordHash() {
    //     return passwordHash;
    // }
    // public void setPasswordHash(String passwordHash) {
    //     this.passwordHash = passwordHash;
    // }
    // public LocalDateTime getCreatedAt() {
    //     return createdAt;
    // }
    // public void setCreatedAt(LocalDateTime createdAt) {
    //     this.createdAt = createdAt;
    // }
    // public LocalDateTime getUpdatedAt() {
    //     return updatedAt;
    // }
    // public void setUpdatedAt(LocalDateTime updatedAt) {
    //     this.updatedAt = updatedAt;
    // }

}
